#!/bin/bash
 
xsetroot -cursor_name left_ptr
sxhkd &
feh --bg-fill /home/ryan/Pictures/mount.png &
picom --experimental-backends --config ~/.config/picom/picom.conf &
/home/ryan/.config/polybar/launch.sh &
xrandr --output DP-4 --mode 1920x1080 --rate 144 && xrandr --output HDMI-0 --mode 1920x1080 --rate 119.98 && xrandr --output DP-4 --primary --right-of HDMI-0 

bspc monitor DP-4 -s HDMI-0 
bspc monitor DP-4 -d  1 2 3 4 5 6 7 8 9
bspc monitor HDMI-0 -d  10
 
bspc config border_width  1
bspc config window_gap		16
 
bspc config split_ratio		0.5
bspc config focus_follows_pointer	true
bspc config pointer_follows_monitor true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme longest_side
 
bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on
